#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Andrew Arensburger
  description: Set up Mac Time Machine volume on TrueNAS

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: Apache-2.0

  min_ansible_version: 2.0

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags:
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.
    - truenas
    - time_machine
    - macos

dependencies: []
