# defaults file for macbackups
---
# Name of the user who owns the backup volume.
backup_user: macbackups
# Backup user's password. This will need to be entered on each Time
# Machine client.
backup_user_passwd: null
backup_user_name: "Mac Time Machine backups"
homes_dir: "/mnt/Pool_1"
vol_pool: null
vol_name: macbackups
allow_hosts: []
deny_hosts:
  - ALL
